name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCS_BRANCH: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '2.7'
    - run: python2 -m pip install sphinx giza
    
    - name: Checkout docs
      uses: actions/checkout@v3
      with:
        repository: mongodocs/docs
        ref: ${{ env.DOCS_BRANCH }}
      
    - name: Build docs
      run: make html

#     - name: Deploy to GitHub Pages
#       uses: JamesIves/github-pages-deploy-action@v4.3.4
#       with:
#         folder: build/${{ env.DOCS_BRANCH }}/html
